#!/bin/sh

new_branch=$1

if [ $new_branch -x ]; then
  echo 'どこだった？';
  read new_branch;
fi

git reset --soft HEAD^
if git show-ref --verify --quiet refs/heads/$new_branch; then
  git checkout $new_branch
else
  git checkout -b $new_branch
fi
git commit
