#!/bin/sh

CURDIR=$(dirname "$(test -L $0 && readlink $0 || echo $0)")
HELPERS=`ls $CURDIR/git-*`
for HELPER in $HELPERS
do
  HELPER=`basename $HELPER | sed -e "s/^git-//"`
  [ $HELPER != "助けて" ] && echo git $HELPER
done
